/*
 * generated by Xtext
 */
package at.ac.tuwien.big.momot.lang.ide

import at.ac.tuwien.big.momot.lang.MOMoTRuntimeModule
import at.ac.tuwien.big.momot.lang.MOMoTStandaloneSetup
import com.google.inject.Guice
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class MOMoTIdeSetup extends MOMoTStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new MOMoTRuntimeModule, new MOMoTIdeModule))
	}
	
}
